name: Update concert calendar

on:
  schedule:
    - cron: "0 3 * * 1"   # Every Monday at 03:00 UTC
  workflow_dispatch:

jobs:
  update-calendar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright
        run: pip install playwright

      - name: Install Playwright Browsers
        run: playwright install --with-deps

      - name: Install Playwright Stealth
        run: pip install playwright-stealth

      - name: Generate concert calendar
        run: python merge.py

      - name: Save calendar
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add calendars/*.ics
          git commit -m "Weekly concert update" || exit 0
          git push
